<a href="https://colab.research.google.com/github/phd-Master/LSTM_RNN_Tutorials_with_Demo/blob/master/Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np 
np.random.seed(1)

input_dim_size = 3
hidden_state_size = 4
batch = 1

W1 = np.random.randn(input_dim_size, hidden_state_size)
W2 = np.random.randn(hidden_state_size, hidden_state_size)
b_h = np.random.randn(hidden_state_size)

Xt = np.random.rand(batch, input_dim_size)
h0 = np.zeros(shape=(batch, hidden_state_size))
 
result = np.tanh(np.dot(Xt, W1) + np.dot(h0, W2) + b_h)
print('W1.shape : {} '.format(W1.shape))
print('W2.shape : {} '.format(W2.shape))
print('Xt.shape : {} '.format(Xt.shape))
print('h0.shape : {} '.format(h0.shape))

print('W1 : {} '.format(W1))
print('W2 : {} '.format(W2))
print('Xt : {} '.format(Xt))
print('h0 : {} '.format(h0))

# now lets stack them together
W3 = np.vstack((W1, W2))

print('nNow, lets stack the weights and the inputs together: ')
print('W3.shape : {}'.format(W3.shape))
print('W3 : {}'.format(W3))

Xth0 = np.hstack((Xt, h0))
print('Xth0.shape: {}'.format(Xth0.shape))
print('Xth0 : {}'.format(Xth0))

result2 = np.tanh(np.dot(Xth0, W3) + b_h)

print('result.shape : {} '.format(result.shape)) 
print('result2.shape : {} '.format(result2.shape)) 

print('result : {} '.format(result)) 
print('result2 : {} '.format(result2))


W1.shape : (3, 4) 
W2.shape : (4, 4) 
Xt.shape : (1, 3) 
h0.shape : (1, 4) 
W1 : [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]] 
W2 : [[-0.3224172  -0.38405435  1.13376944 -1.09989127]
 [-0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943]] 
Xt : [[0.01936696 0.67883553 0.21162812]] 
h0 : [[0. 0. 0. 0.]] 
nNow, lets stack the weights and the inputs together: 
W3.shape : (7, 4)
W3 : [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]
 [-0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943]]
Xth0.shape: (1, 7)
Xth0 : [[0.01936696 0.67883553 0.